<a href="https://colab.research.google.com/github/sabaadrees/Market-efficiencies/blob/main/market_efficiencies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install yfinance
import numpy as np
import pandas as pd
import yfinance as yf
import numpy as np
import pandas as pd
import yfinance as yf
import scipy.stats as sps 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# New Section

In [ ]:
###Quickly test for market efficiencies on any return series - run test application

In [ ]:
### FOR INDICES USE ^ WITH TICKER AND FOR INDIVIDUAL TICKERS LIKE THIS 'AAPL'

In [ ]:
ticker = '^GSPC'
start = '2010-12-31'
end = '2020-12-31'
prices = np.array(yf.download(ticker, start, end)['Adj Close'])

[*********************100%***********************]  1 of 1 completed


In [ ]:
prices


array([1257.64001465, 1271.86999512, 1270.19995117, ..., 3735.36010742,
       3727.04003906, 3732.04003906])

In [ ]:

returns = prices[1:]/prices[:-1] -1
returns = returns[returns !=0]
n = len(returns)
signs = np.sign(returns)


In [ ]:
returns

array([ 0.01131483, -0.00131306,  0.00500717, ...,  0.00872253,
       -0.00222738,  0.00134155])

In [ ]:
signs

array([ 1., -1.,  1., ...,  1., -1.,  1.])

In [ ]:
runs = signs[1:] - signs[:-1]

In [ ]:
runs

array([-2.,  2., -2., ...,  0., -2.,  2.])

In [ ]:

observed_runs = np.count_nonzero(runs == 2) + np.count_nonzero(runs == -2) + 1

In [ ]:
observed_runs

1303

In [ ]:
postive_returns = np.count_nonzero(signs == 1)
negative_returns = np.count_nonzero(signs == -1)
expected_runs = 2*postive_returns*negative_returns/n +1

In [ ]:
expected_runs

1246.5666003976144

In [ ]:
stdev_runs = expected_runs*(expected_runs -1)/(n -1) **(1/2)

In [ ]:
z_stat = (observed_runs - expected_runs)/stdev_runs
p_value = 2*(1- sps.norm.cdf(abs(z_stat)))
if p_value > 0.1:
    print('market is efficient')
elif z_stat > 0:
    print ('market is mean-reverting')
else:
    print ('market is trending')
print(observed_runs, int(expected_runs), round(stdev_runs, 2), round(z_stat, 4), round(p_value, 4))

market is efficient
1303 1246 30967.05 0.0018 0.9985
